name = "saltnet-render-service"
main = "src/worker.ts"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
RENDER_IMAGE_CACHE_SECONDS = "600"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[assets]
directory = "../public"
binding = "ASSETS"

