<script setup lang="ts">
    import { defineProps } from "vue";
    import ScoreSection from "@/components/data/chart/ScoreSection.vue";
    import RatingPlate from "@/components/data/user/RatingPlate.vue";
    import type { Chart } from "@/components/data/music/type";

    const { b50SdCharts, b50DxCharts, playerName, playerSecondaryName, playerRating } = defineProps<{
        b50SdCharts: Chart[];
        b50DxCharts: Chart[];
        playerName: string;
        playerSecondaryName?: string | null;
        playerRating?: number | null;
    }>();
</script>

<template>
    <div class="wrapper">
        <div class="player-profile mdui-theme-light" id="player-b50-for-rendering">
            <div class="player-b50">
                <div class="player-header">
                    <div class="player-info">
                        <div class="player-name-container">
                            <span class="player-name">
                                {{ playerName }}
                            </span>
                            <span
                                v-if="playerSecondaryName"
                                class="player-original-name"
                            >
                                {{ playerSecondaryName }}
                            </span>
                        </div>
                        <RatingPlate v-if="playerRating != null" :ra="playerRating" />
                    </div>
                    <div class="saltnet-info">
                        <div>
                            <span class="saltnet-generated">Generated by SaltNet</span>
                            <span class="saltnet-url">salt.realtvop.top</span>
                        </div>
                        <img src="https://salt.realtvop.top/favicon.png" />
                    </div>
                </div>
                <ScoreSection
                    v-if="b50SdCharts.length"
                    title="旧版本成绩"
                    :scores="b50SdCharts"
                    rendering
                />
                <ScoreSection
                    v-if="b50DxCharts.length"
                    title="新版本成绩"
                    :scores="b50DxCharts"
                    rendering
                />
                <p
                    v-if="!(b50SdCharts.length || b50DxCharts.length)"
                    style="text-align: center; color: orange; margin-top: 20px"
                >
                    未更新成绩或成绩更新失败，请到“用户”更新成绩
                </p>
            </div>
        </div>
    </div>
</template>

<style scoped>
    .wrapper {
        width: 1175px;
        height: 1365px;
    }

    .player-profile {
        padding-top: 20px;
        width: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        box-sizing: border-box;
        overflow: hidden;
        background-image: url("/b50_background.png");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        min-height: 100vh;
    }

    .player-b50 {
        width: 100%;
        max-width: 1200px;
        box-sizing: border-box;
        padding-bottom: 5vh;
    }

    .player-header {
        display: flex;
        align-items: center;
        flex-wrap: wrap;
        flex-direction: row;
        margin-bottom: 24px;
        gap: 1.5rem;
        padding: 0 30px;
        justify-content: space-between;
    }

    .player-info {
        display: flex;
        align-items: center;
        gap: 1.5rem;
    }

    .player-name-container {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        gap: 4px;
    }

    .player-name {
        font-size: 2em;
        font-weight: bold;
    }

    .player-original-name {
        font-size: 0.9em;
        color: var(--mdui-color-on-surface-variant);
        font-weight: normal;
    }

    .saltnet-info {
        display: flex;
        flex-direction: row;
        align-items: center;
        gap: 0.5rem;
    }
    .saltnet-info > div {
        display: flex;
        flex-direction: column;
        align-items: flex-end;
    }
    .saltnet-info > div > .saltnet-generated {
        font-weight: 600;
        margin-bottom: -0.25rem;
    }
    .saltnet-info > div > .saltnet-info {
        font-size: small;
    }
    .saltnet-info > img {
        height: 3rem;
    }
</style>
