import type { B50RenderChart, B50RenderPayload } from "./b50-payload";

const WIDTH = 1175;
const HEIGHT = 1365;
const DEFAULT_SITE_ORIGIN = "https://salt.realtvop.top";

export interface B50RenderTemplateOptions {
    siteOrigin?: string;
}

export const B50_RENDER_SIZE = {
    width: WIDTH,
    height: HEIGHT,
};

export function renderB50Html(
    payload: B50RenderPayload,
    options: B50RenderTemplateOptions = {}
): string {
    const modeLabel = payload.modeLabel && payload.modeLabel !== "B50" ? payload.modeLabel : "";
    const siteOrigin = normalizeOrigin(options.siteOrigin ?? DEFAULT_SITE_ORIGIN);
    return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>${renderStyles(payload.showDxScore, siteOrigin)}</style>
</head>
<body>
<main class="page">
  <section class="header">
    <div class="player">
      <div>
        <div class="name">${escapeHtml(payload.playerName)}</div>
        ${payload.playerSecondaryName ? `<div class="secondary">${escapeHtml(payload.playerSecondaryName)}</div>` : ""}
      </div>
      ${typeof payload.playerRating === "number" ? renderRating(payload.playerRating) : ""}
      ${modeLabel ? `<div class="mode">${escapeHtml(modeLabel)}</div>` : ""}
    </div>
    <div class="brand">
      <div>
        <div class="generated">Generated by SaltNet</div>
        <div class="url">salt.realtvop.top</div>
      </div>
      <img class="logo" src="${siteOrigin}/favicon.png">
    </div>
  </section>
  ${renderSection("旧版本成绩", payload.sd, payload.showDxScore, siteOrigin)}
  ${renderSection("新版本成绩", payload.dx, payload.showDxScore, siteOrigin)}
</main>
</body>
</html>`;
}

function renderSection(
    title: string,
    charts: B50RenderChart[],
    showDxScore: boolean,
    siteOrigin: string
): string {
    if (!charts.length) return "";
    const stats = getStats(charts);
    return `<section class="section">
  <h2>${title}
    <span class="stats">
      <span>${stats.total}</span>
      <span>${stats.levelRange}</span>
      <span>平均: ${stats.average}</span>
      <span>中位数: ${stats.median}</span>
      <span>极差: ${stats.range}</span>
    </span>
  </h2>
  <div class="grid">${charts.map(chart => renderCard(chart, showDxScore, siteOrigin)).join("")}</div>
</section>`;
}

function renderCard(chart: B50RenderChart, showDxScore: boolean, siteOrigin: string): string {
    const achievement =
        typeof chart.achievements === "number" ? chart.achievements.toFixed(4) : "-";
    const stars = renderDxStars(chart, showDxScore, siteOrigin);
    return `<article class="card ${showDxScore ? "with-dx" : "without-dx"}">
  <img class="cover" src="${getCoverUrl(chart.songId)}">
  <div class="details">
    <div class="pill">
      <span class="type ${chart.type === "DX" ? "dx" : "sd"}">${escapeHtml(chart.type)}</span>
      <span class="level grade-${chart.levelIndex}">${formatNumber(chart.ds, 1)}</span>
      <span class="rating">${Math.round(chart.ra)}</span>
    </div>
    <div class="title">${escapeHtml(chart.title)}</div>
    <div class="achievement">${achievement}<span>%</span></div>
    <div class="badges">
      <div class="rank">${chart.rate ? `<img src="${siteOrigin}/icons/${chart.rate.replace("p", "plus")}.png">` : stars}</div>
      <div class="badge">${chart.fc ? `<img src="${siteOrigin}/icons/music_icon_${chart.fc}.png">` : ""}</div>
      <div class="badge">${chart.fs ? `<img src="${siteOrigin}/icons/music_icon_${chart.fs.replace("sd", "dx")}.png">` : ""}</div>
    </div>
    ${
        showDxScore
            ? `<div class="dxscore">${stars}<span>${chart.deluxeScore ?? "-"} / ${chart.deluxeScoreMax ?? "-"}</span></div>`
            : ""
    }
  </div>
</article>`;
}

function renderDxStars(chart: B50RenderChart, showDxScore: boolean, siteOrigin: string): string {
    if (typeof chart.deluxeScore !== "number" || typeof chart.deluxeScoreMax !== "number") {
        return "";
    }
    const tier = getDeluxeScoreTier(chart.deluxeScore, chart.deluxeScoreMax);
    if (!tier) return "";
    const star = tier < 3 ? "star1" : tier < 5 ? "star2" : "star3";
    const className = showDxScore ? "star" : "mini-star";
    return Array.from(
        { length: tier },
        () => `<img class="${className}" src="${siteOrigin}/icons/${star}.png">`
    ).join("");
}

function renderRating(rating: number): string {
    const digits = Math.round(rating).toString();
    return `<div class="rating-plate plate-${getPlateId(rating)}">${escapeHtml(digits)}</div>`;
}

function getStats(charts: B50RenderChart[]) {
    const ratings = charts.map(chart => Math.round(chart.ra)).sort((a, b) => a - b);
    const constants = charts.map(chart => chart.ds).sort((a, b) => a - b);
    const total = ratings.reduce((sum, rating) => sum + rating, 0);
    const middle = Math.floor(ratings.length / 2);
    const median =
        ratings.length % 2 === 0 ? (ratings[middle - 1] + ratings[middle]) / 2 : ratings[middle];

    return {
        total,
        average: (total / ratings.length).toFixed(2),
        median,
        range: ratings[ratings.length - 1] - ratings[0],
        levelRange: `${formatNumber(constants[0], 1)}~${formatNumber(constants[constants.length - 1], 1)}`,
    };
}

function getCoverUrl(songId: number): string {
    return `https://meta.salt.realtvop.top/covers/${padId(songId % 10000, 6)}.png`;
}

function padId(id: number, length: number): string {
    return id.toString().padStart(length, "0");
}

function getPlateId(rating: number): string {
    const levels = [1000, 2000, 4000, 7000, 10000, 12000, 13000, 14000, 14500, 15000];
    if (rating < levels[0]) return "01";
    if (rating >= levels[9]) return "11";
    const plateIndex = levels.findIndex(
        (threshold, index) => rating >= threshold && rating < levels[index + 1]
    );
    return plateIndex >= 0 ? (plateIndex + 2).toString().padStart(2, "0") : "00";
}

function getDeluxeScoreTier(deluxeScore: number, deluxeScoreMax: number): number {
    const percent = deluxeScore / deluxeScoreMax;
    if (percent >= 0.97) return 5;
    if (percent >= 0.95) return 4;
    if (percent >= 0.93) return 3;
    if (percent >= 0.9) return 2;
    if (percent >= 0.85) return 1;
    return 0;
}

function formatNumber(value: number, digits: number): string {
    return value.toFixed(digits);
}

function escapeHtml(value: string): string {
    return value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
}

function normalizeOrigin(origin: string): string {
    return origin.replace(/\/+$/, "");
}

function renderStyles(showDxScore: boolean, siteOrigin: string): string {
    return `
* { box-sizing: border-box; }
html, body { width: ${WIDTH}px; height: ${HEIGHT}px; margin: 0; }
body {
  font-family: "Noto Sans SC", "Noto Sans JP", "Noto Sans TC", sans-serif;
  color: #222;
  background: #eef6fb;
}
.page {
  width: ${WIDTH}px;
  height: ${HEIGHT}px;
  overflow: hidden;
  padding: 20px 30px 40px;
  background-image: linear-gradient(rgba(255,255,255,.72), rgba(255,255,255,.78)), url("${siteOrigin}/b50_background.png");
  background-size: cover;
  background-position: center;
}
.header { display: flex; align-items: center; justify-content: space-between; gap: 24px; margin-bottom: 24px; }
.player { display: flex; align-items: center; gap: 22px; min-width: 0; }
.name { font-size: 32px; line-height: 1.1; font-weight: 800; max-width: 520px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.secondary { margin-top: 4px; font-size: 15px; color: #58616b; max-width: 520px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.mode { border: 1px solid rgba(35, 47, 62, .16); background: rgba(255,255,255,.76); border-radius: 999px; padding: 6px 12px; font-size: 16px; font-weight: 700; }
.brand { display: flex; align-items: center; gap: 9px; text-align: right; flex-shrink: 0; }
.generated { font-size: 16px; font-weight: 800; margin-bottom: -2px; }
.url { font-size: 13px; color: #5d6670; }
.logo { width: 48px; height: 48px; }
.rating-plate {
  min-width: 125px;
  height: 25px;
  border-radius: 7px;
  padding: 2px 8px 0 48px;
  color: #fcd41b;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 16px;
  font-weight: 900;
  letter-spacing: 2px;
  line-height: 23px;
  text-align: center;
  box-shadow: inset 0 1px 0 rgba(255,255,255,.55), 0 2px 8px rgba(0,0,0,.12);
}
.plate-01 { background: linear-gradient(90deg, #6f7880, #a7b0b8); }
.plate-02 { background: linear-gradient(90deg, #415d7d, #79a7d8); }
.plate-03 { background: linear-gradient(90deg, #3b8752, #91d977); }
.plate-04 { background: linear-gradient(90deg, #9a6a24, #eac267); }
.plate-05 { background: linear-gradient(90deg, #a85c67, #f39aa4); }
.plate-06 { background: linear-gradient(90deg, #8253a3, #d29af4); }
.plate-07 { background: linear-gradient(90deg, #b45d22, #ffb15e); }
.plate-08 { background: linear-gradient(90deg, #2f7e8f, #60d6e8); }
.plate-09 { background: linear-gradient(90deg, #bc8d17, #ffe066); }
.plate-10 { background: linear-gradient(90deg, #d24f7f, #ff9bbd); }
.plate-11 { background: linear-gradient(90deg, #1e1e2c, #8e92e1); }
.section { margin-top: 16px; }
h2 { display: flex; align-items: baseline; gap: 15px; margin: 0 0 12px; font-size: 24px; line-height: 1.2; }
.stats { display: flex; gap: 10px; flex-wrap: wrap; font-size: 14px; font-weight: 400; color: #47515c; }
.grid { display: grid; grid-template-columns: repeat(5, 210px); gap: 12px; justify-content: center; }
.card {
  width: 210px;
  min-height: ${showDxScore ? 90 : 85}px;
  display: flex;
  overflow: hidden;
  border-radius: 4px;
  background: #f0f0f0;
  box-shadow: 0 1px 3px rgba(0,0,0,.22), 0 2px 8px rgba(0,0,0,.12);
}
.cover { width: 40%; object-fit: cover; object-position: center; flex: 0 0 40%; }
.details { width: 60%; display: flex; flex-direction: column; padding: 6px; min-width: 0; }
.pill { display: flex; height: ${showDxScore ? 12 : 15}px; border-radius: 8px; overflow: hidden; margin-left: 2px; width: calc(100% - 2px); flex-shrink: 0; }
.pill span { display: flex; align-items: center; justify-content: center; font-weight: 900; font-size: ${showDxScore ? 9.5 : 9}px; line-height: 1; padding: 0 3px; color: #fff; }
.type { flex: .5; background: #63acf8; }
.type.dx { background: #fff; color: #eb5639; }
.level { flex: .75; }
.rating { flex: 1; background: linear-gradient(90deg, #ff9933 0%, #ff6600 100%); }
.grade-0 { background: #96d767; }
.grade-1 { background: #eeba41; }
.grade-2 { background: #ef888f; }
.grade-3 { background: #b54fdf; }
.grade-4 { background: #d3acf9; }
.grade-5 { background: #ee78f6; }
.grade-10 { background: #ff6b9b; }
.title { margin-top: ${showDxScore ? 2 : 3}px; font-size: ${showDxScore ? 9 : 10.5}px; font-weight: 800; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.achievement { margin: 1px 0 2px; font-size: ${showDxScore ? 16.5 : 19.5}px; line-height: 1; font-weight: 900; white-space: nowrap; overflow: hidden; }
.achievement span { font-size: ${showDxScore ? 11.5 : 12}px; }
.badges { display: flex; align-items: center; justify-content: space-around; }
.rank, .badge { width: ${showDxScore ? 19.5 : 22.5}px; height: ${showDxScore ? 19.5 : 22.5}px; display: flex; align-items: center; justify-content: center; position: relative; }
.badge { border-radius: 50%; background: #ddd; overflow: hidden; }
.rank img, .badge img { width: 100%; height: 100%; object-fit: contain; }
.mini-star { width: auto !important; height: 7px !important; margin: 0 .5px; }
.dxscore { display: flex; align-items: center; margin-top: 2px; font-size: 9px; line-height: 1; min-height: 10px; }
.dxscore span { margin-left: auto; }
.star { width: auto !important; height: 9px !important; margin-right: 1px; }
`;
}
