import type { Font } from "takumi-js";
import type { B50RenderPayload } from "./b50-payload";

const GOOGLE_FONTS_ORIGIN = "https://fonts.googleapis.com/css2";
const FONT_FAMILY_QUERIES = [
    "Noto Sans SC:wght@400;700;800;900",
    "Noto Sans JP:wght@400;700;800;900",
    "Noto Sans TC:wght@400;700;800;900",
    "JetBrains Mono:wght@700;800;900",
];
const STATIC_RENDER_TEXT =
    "Generated by SaltNet salt.realtvop.top B50 AP50 FC50 旧版本成绩 新版本成绩 平均 中位数 极差 未更新成绩或成绩更新失败 请到用户更新成绩 0123456789.%/-+DXSD";
const MAX_TEXT_QUERY_LENGTH = 1600;

export const B50_FONT_FAMILIES = ["Noto Sans SC", "Noto Sans JP", "Noto Sans TC", "JetBrains Mono"];

export const B50_RENDER_LANG = "zh-CN";

const fontPromises = new Map<string, Promise<Font[]>>();

export function loadB50RenderFonts(payload?: B50RenderPayload): Promise<Font[]> {
    const text = collectB50RenderText(payload);
    const cacheKey = text.length > MAX_TEXT_QUERY_LENGTH ? "" : text;
    let promise = fontPromises.get(cacheKey);
    if (!promise) {
        promise = fetchGoogleFonts(cacheKey);
        fontPromises.set(cacheKey, promise);
    }

    return promise;
}

export function collectB50RenderText(payload?: B50RenderPayload): string {
    const chunks = [STATIC_RENDER_TEXT];
    if (payload) {
        chunks.push(payload.playerName);
        if (payload.playerSecondaryName) chunks.push(payload.playerSecondaryName);
        if (payload.modeLabel) chunks.push(payload.modeLabel);
        for (const chart of [...payload.sd, ...payload.dx]) {
            chunks.push(chart.title, chart.type, chart.rate, chart.fc, chart.fs);
        }
    }

    return Array.from(new Set(chunks.join("").replace(/\s+/g, ""))).join("");
}

export function createB50GoogleFontsCssUrl(text: string): string {
    const params = new URLSearchParams();
    for (const family of FONT_FAMILY_QUERIES) params.append("family", family);
    if (text) params.set("text", text);
    params.set("display", "swap");
    return `${GOOGLE_FONTS_ORIGIN}?${params.toString()}`;
}

async function fetchGoogleFonts(text: string): Promise<Font[]> {
    const response = await fetch(createB50GoogleFontsCssUrl(text));
    if (!response.ok) return [];

    const css = await response.text();
    const faces = parseFontFaces(css);
    const loaded = await Promise.allSettled(
        faces.map(async face => {
            const fontResponse = await fetch(face.url);
            if (!fontResponse.ok) throw new Error(`Font fetch failed: ${fontResponse.status}`);
            return {
                name: `${face.family} ${face.weight} ${face.index}`,
                data: await fontResponse.arrayBuffer(),
                weight: face.weight,
                style: face.style,
                subsetOf: face.family,
            } satisfies Font;
        })
    );

    const fonts: Font[] = [];
    for (const result of loaded) {
        if (result.status === "fulfilled") fonts.push(result.value);
    }
    return fonts;
}

function parseFontFaces(css: string) {
    const blocks = css.match(/@font-face\s*{[^}]+}/g) ?? [];
    return blocks
        .map((block, index) => {
            const family = readCssValue(block, "font-family")?.replace(/^['"]|['"]$/g, "");
            const weight = Number.parseInt(readCssValue(block, "font-weight") ?? "", 10);
            const style = readCssValue(block, "font-style") ?? "normal";
            const url = block.match(/url\(([^)]+)\)/)?.[1]?.replace(/^['"]|['"]$/g, "");

            if (!family || !url || !Number.isFinite(weight)) return null;
            return {
                family,
                index,
                weight,
                style,
                url,
            };
        })
        .filter(
            (
                face
            ): face is {
                family: string;
                index: number;
                weight: number;
                style: string;
                url: string;
            } => face !== null
        );
}

function readCssValue(block: string, property: string): string | null {
    const match = block.match(new RegExp(`${property}\\s*:\\s*([^;]+);`));
    return match?.[1]?.trim() ?? null;
}
