import type { CSSProperties } from "react";
import type { B50RenderChart, B50RenderPayload } from "./b50-payload";
import plates from "../../src/assets/plates.json";

const DESIGN_WIDTH = 1175;
const DESIGN_HEIGHT = 1365;
export const B50_RENDER_SCALE = 2;
const DEFAULT_SITE_ORIGIN = "https://salt.realtvop.top";

export const B50_DESIGN_SIZE = {
    width: DESIGN_WIDTH,
    height: DESIGN_HEIGHT,
};

export const B50_RENDER_SIZE = {
    width: DESIGN_WIDTH * B50_RENDER_SCALE,
    height: DESIGN_HEIGHT * B50_RENDER_SCALE,
};

export interface B50RenderImageOptions {
    siteOrigin?: string;
}

interface B50RenderImageProps {
    payload: B50RenderPayload;
    options?: B50RenderImageOptions;
}

export function B50RenderImage({ payload, options = {} }: B50RenderImageProps) {
    const siteOrigin = normalizeOrigin(options.siteOrigin ?? DEFAULT_SITE_ORIGIN);
    const modeLabel = payload.modeLabel && payload.modeLabel !== "B50" ? payload.modeLabel : "";

    return (
        <main style={styles.canvas}>
            <div style={styles.scaledContent}>
                <div style={styles.page(siteOrigin)}>
                    <section style={styles.header}>
                        <div style={styles.player}>
                            <div style={styles.playerNames}>
                                <div style={styles.name}>{payload.playerName}</div>
                                {payload.playerSecondaryName ? (
                                    <div style={styles.secondary}>
                                        {payload.playerSecondaryName}
                                    </div>
                                ) : null}
                            </div>
                            {typeof payload.playerRating === "number" ? (
                                <RatingPlate rating={payload.playerRating} />
                            ) : null}
                            {modeLabel ? <div style={styles.mode}>{modeLabel}</div> : null}
                        </div>
                        <div style={styles.brand}>
                            <div>
                                <div style={styles.generated}>Generated by SaltNet</div>
                                <div style={styles.url}>salt.realtvop.top</div>
                            </div>
                            <img style={styles.logo} src={`${siteOrigin}/favicon.png`} />
                        </div>
                    </section>

                    <ScoreSection
                        title="旧版本成绩"
                        charts={payload.sd}
                        showDxScore={payload.showDxScore}
                        siteOrigin={siteOrigin}
                    />
                    <ScoreSection
                        title="新版本成绩"
                        charts={payload.dx}
                        showDxScore={payload.showDxScore}
                        siteOrigin={siteOrigin}
                    />
                    {!payload.sd.length && !payload.dx.length ? (
                        <p style={styles.emptyMessage}>
                            未更新成绩或成绩更新失败，请到“用户”更新成绩
                        </p>
                    ) : null}
                </div>
            </div>
        </main>
    );
}

function ScoreSection({
    title,
    charts,
    showDxScore,
    siteOrigin,
}: {
    title: string;
    charts: B50RenderChart[];
    showDxScore: boolean;
    siteOrigin: string;
}) {
    if (!charts.length) return null;
    const stats = getStats(charts);

    return (
        <section style={styles.section}>
            <h2 style={styles.sectionTitle}>
                {title}
                <span style={styles.stats}>
                    <span>{stats.total}</span>
                    <span>{stats.levelRange}</span>
                    <span>平均: {stats.average}</span>
                    <span>中位数: {stats.median}</span>
                    <span>极差: {stats.range}</span>
                </span>
            </h2>
            <div style={styles.grid}>
                {charts.map((chart, index) => (
                    <ScoreCard
                        key={`${chart.songId}-${chart.levelIndex}-${index}`}
                        chart={chart}
                        showDxScore={showDxScore}
                        siteOrigin={siteOrigin}
                    />
                ))}
            </div>
        </section>
    );
}

function ScoreCard({
    chart,
    showDxScore,
    siteOrigin,
}: {
    chart: B50RenderChart;
    showDxScore: boolean;
    siteOrigin: string;
}) {
    const isPlayed = typeof chart.achievements === "number";
    const achievement =
        typeof chart.achievements === "number" ? chart.achievements.toFixed(4) : "-";

    const dxScoreStars =
        typeof chart.deluxeScore === "number" && typeof chart.deluxeScoreMax === "number"
            ? getDeluxeScoreTier(chart.deluxeScore, chart.deluxeScoreMax)
            : null;

    const chartTypeSpanStyle: CSSProperties =
        chart.type === "DX"
            ? {
                  background: "linear-gradient(-20deg, #eb5639 55%, #efb03e 45%)",
                  WebkitBackgroundClip: "text",
                  backgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                  display: "inline-block",
              }
            : {};

    const typeSpan =
        chart.type === "DX" ? <span style={chartTypeSpanStyle}>{chart.type}</span> : chart.type;

    return (
        <div style={styles.cardWrapper}>
            <article style={styles.card(showDxScore)}>
                <div style={styles.songJacketSection}>
                    <img
                        style={styles.songJacketImage}
                        src={getCoverUrl(chart.songId)}
                        alt={chart.title}
                        crossOrigin="anonymous"
                    />
                </div>
                <div style={styles.details(showDxScore)}>
                    <div style={styles.resultHeader(showDxScore)}>
                        <div style={styles.headerPill(showDxScore)}>
                            <div style={{ ...styles.pillSection, ...styles.charttype(chart.type) }}>
                                {typeSpan}
                            </div>
                            <div
                                style={{ ...styles.pillSection, ...styles.level(chart.levelIndex) }}
                            >
                                {formatNumber(chart.ds, 1)}
                            </div>
                            <div style={{ ...styles.pillSection, ...styles.points }}>
                                {Math.round(chart.ra)}
                            </div>
                        </div>
                    </div>
                    <div style={styles.songName(showDxScore)}>{chart.title}</div>
                    <div style={styles.achievement(showDxScore)}>
                        {achievement}
                        {isPlayed ? (
                            <span style={styles.percentageMark(showDxScore)}>%</span>
                        ) : null}
                    </div>
                    <div style={styles.achievementBadges}>
                        <div style={styles.rankAchievement(showDxScore)}>
                            {chart.rate ? (
                                <img
                                    style={styles.achievementIcon}
                                    src={`${siteOrigin}/icons/${chart.rate.replace("p", "plus")}.png`}
                                />
                            ) : null}
                            {!showDxScore && dxScoreStars !== null ? (
                                <div style={styles.dxScoreStarsMini}>
                                    <DxStars
                                        tier={dxScoreStars}
                                        isMini={true}
                                        siteOrigin={siteOrigin}
                                    />
                                </div>
                            ) : null}
                        </div>
                        <div style={styles.fcAchievement(showDxScore)}>
                            {chart.fc ? (
                                <img
                                    style={styles.achievementIcon}
                                    src={`${siteOrigin}/icons/music_icon_${chart.fc}.png`}
                                />
                            ) : null}
                        </div>
                        <div style={styles.syncAchievement(showDxScore)}>
                            {chart.fs ? (
                                <img
                                    style={styles.achievementIcon}
                                    src={`${siteOrigin}/icons/music_icon_${chart.fs.replace("sd", "dx")}.png`}
                                />
                            ) : null}
                        </div>
                    </div>
                    {showDxScore ? (
                        <div style={styles.dxScore}>
                            {dxScoreStars !== null ? <span>&nbsp;</span> : null}
                            {dxScoreStars !== null ? (
                                <DxStars
                                    tier={dxScoreStars}
                                    isMini={false}
                                    siteOrigin={siteOrigin}
                                />
                            ) : null}
                            {chart.deluxeScore !== undefined ? (
                                <span style={styles.dxScoreLabel}>
                                    {isPlayed ? chart.deluxeScore : "-"} / {chart.deluxeScoreMax}
                                </span>
                            ) : null}
                            {dxScoreStars !== null ? <span>&nbsp;&nbsp;</span> : null}
                        </div>
                    ) : null}
                </div>
            </article>
        </div>
    );
}

function DxStars({
    tier,
    isMini,
    siteOrigin,
}: {
    tier: number;
    isMini: boolean;
    siteOrigin: string;
}) {
    if (!tier) return null;

    const starImg = getDeluxeScoreStarsImg(tier);
    const starStyle = isMini ? styles.dxScoreStarMini : styles.dxScoreStar;

    return (
        <>
            {Array.from({ length: tier }, (_, index) => (
                <img key={index} style={starStyle} src={`${siteOrigin}${starImg}`} />
            ))}
        </>
    );
}

function RatingPlate({ rating }: { rating: number }) {
    const ratingStr = Math.round(rating).toString();
    const plateId = getPlateId(rating);
    const href = (plates as Record<string, string>)[plateId] ?? plates["01"];

    return (
        <div
            style={{ position: "relative", width: 125, height: 25, display: "flex", marginLeft: 5 }}
        >
            <img
                src={href}
                style={{
                    position: "absolute",
                    top: 0,
                    left: 0,
                    width: 125,
                    height: 25,
                }}
            />
            <div
                style={{
                    position: "absolute",
                    top: 0,
                    left: 55,
                    width: 65,
                    height: 25,
                    color: "#fcd41b",
                    fontFamily:
                        '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
                    fontSize: 16,
                    fontWeight: 900,
                    letterSpacing: 2.2,
                    lineHeight: "23px",
                    display: "flex",
                    justifyContent: "flex-end",
                    alignItems: "center",
                    boxSizing: "border-box",
                    paddingRight: 2,
                }}
            >
                {ratingStr}
            </div>
        </div>
    );
}

function getStats(charts: B50RenderChart[]) {
    const ratings = charts.map(chart => Math.round(chart.ra)).sort((a, b) => a - b);
    const constants = charts.map(chart => chart.ds).sort((a, b) => a - b);
    const total = ratings.reduce((sum, rating) => sum + rating, 0);
    const middle = Math.floor(ratings.length / 2);
    const median =
        ratings.length % 2 === 0 ? (ratings[middle - 1] + ratings[middle]) / 2 : ratings[middle];

    return {
        total,
        average: (total / ratings.length).toFixed(2),
        median,
        range: ratings[ratings.length - 1] - ratings[0],
        levelRange: `${formatNumber(constants[0], 1)}~${formatNumber(constants[constants.length - 1], 1)}`,
    };
}

function getCoverUrl(songId: number): string {
    return `https://meta.salt.realtvop.top/covers/${padId(songId % 10000, 6)}.png`;
}

function padId(id: number, length: number): string {
    return id.toString().padStart(length, "0");
}

function getPlateId(rating: number): string {
    const levels = [1000, 2000, 4000, 7000, 10000, 12000, 13000, 14000, 14500, 15000];
    if (rating < levels[0]) return "01";
    if (rating >= levels[9]) return "11";
    const plateIndex = levels.findIndex(
        (threshold, index) => rating >= threshold && rating < levels[index + 1]
    );
    return plateIndex >= 0 ? (plateIndex + 2).toString().padStart(2, "0") : "00";
}

function getDeluxeScoreTier(deluxeScore: number, deluxeScoreMax: number): number {
    const percent = deluxeScore / deluxeScoreMax;
    if (percent >= 0.97) return 5;
    if (percent >= 0.95) return 4;
    if (percent >= 0.93) return 3;
    if (percent >= 0.9) return 2;
    if (percent >= 0.85) return 1;
    return 0;
}

function getDeluxeScoreStarsImg(tier: number): string {
    if (tier < 3) return "/icons/star1.png";
    if (tier < 5) return "/icons/star2.png";
    return "/icons/star3.png";
}

function formatNumber(value: number, digits: number): string {
    return value.toFixed(digits);
}

function normalizeOrigin(origin: string): string {
    return origin.replace(/\/+$/, "");
}

const difficultyColors: Record<number, string> = {
    0: "#96d767",
    1: "#eeba41",
    2: "#ef888f",
    3: "#b54fdf",
    4: "#d3acf9",
    5: "#ee78f6",
    10: "#ff6b9b",
};

const plateColors: Record<string, string> = {
    "01": "linear-gradient(90deg, #6f7880, #a7b0b8)",
    "02": "linear-gradient(90deg, #415d7d, #79a7d8)",
    "03": "linear-gradient(90deg, #3b8752, #91d977)",
    "04": "linear-gradient(90deg, #9a6a24, #eac267)",
    "05": "linear-gradient(90deg, #a85c67, #f39aa4)",
    "06": "linear-gradient(90deg, #8253a3, #d29af4)",
    "07": "linear-gradient(90deg, #b45d22, #ffb15e)",
    "08": "linear-gradient(90deg, #2f7e8f, #60d6e8)",
    "09": "linear-gradient(90deg, #bc8d17, #ffe066)",
    "10": "linear-gradient(90deg, #d24f7f, #ff9bbd)",
    "11": "linear-gradient(90deg, #1e1e2c, #8e92e1)",
};

const styles = {
    canvas: {
        width: B50_RENDER_SIZE.width,
        height: B50_RENDER_SIZE.height,
        overflow: "hidden",
        backgroundColor: "#eef6fb",
    } satisfies CSSProperties,
    scaledContent: {
        width: DESIGN_WIDTH,
        height: DESIGN_HEIGHT,
        transform: `scale(${B50_RENDER_SCALE})`,
        transformOrigin: "top left",
    } satisfies CSSProperties,
    page: (siteOrigin: string): CSSProperties => ({
        width: DESIGN_WIDTH,
        height: DESIGN_HEIGHT,
        overflow: "hidden",
        padding: "20px 30px 40px",
        color: "#222",
        backgroundColor: "#eef6fb",
        backgroundImage: `linear-gradient(rgba(255,255,255,.72), rgba(255,255,255,.78)), url("${siteOrigin}/b50_background.png")`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        fontFamily: '"Noto Sans SC", "Noto Sans JP", "Noto Sans TC", sans-serif',
        boxSizing: "border-box",
    }),
    emptyMessage: {
        marginTop: 20,
        textAlign: "center",
        color: "orange",
        fontSize: 18,
    } satisfies CSSProperties,
    header: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 24,
        marginBottom: 24,
    } satisfies CSSProperties,
    player: {
        display: "flex",
        alignItems: "center",
        gap: 22,
        minWidth: 0,
    } satisfies CSSProperties,
    playerNames: {
        display: "flex",
        flexDirection: "column",
        minWidth: 0,
    } satisfies CSSProperties,
    name: {
        fontSize: 32,
        lineHeight: 1.1,
        fontWeight: 800,
        maxWidth: 520,
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
    } satisfies CSSProperties,
    secondary: {
        marginTop: 4,
        fontSize: 15,
        color: "#58616b",
        maxWidth: 520,
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
    } satisfies CSSProperties,
    mode: {
        border: "1px solid rgba(35, 47, 62, .16)",
        background: "rgba(255,255,255,.76)",
        borderRadius: 999,
        padding: "6px 12px",
        fontSize: 16,
        fontWeight: 700,
    } satisfies CSSProperties,
    brand: {
        display: "flex",
        alignItems: "center",
        gap: 9,
        textAlign: "right",
        flexShrink: 0,
    } satisfies CSSProperties,
    generated: {
        fontSize: 16,
        fontWeight: 800,
        marginBottom: -2,
    } satisfies CSSProperties,
    url: {
        fontSize: 13,
        color: "#5d6670",
    } satisfies CSSProperties,
    logo: {
        width: 48,
        height: 48,
    } satisfies CSSProperties,
    ratingPlate: {
        minWidth: 125,
        height: 25,
        borderRadius: 7,
        padding: "2px 8px 0 48px",
        color: "#fcd41b",
        fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
        fontSize: 16,
        fontWeight: 900,
        letterSpacing: 2,
        lineHeight: "23px",
        textAlign: "center",
        boxShadow: "inset 0 1px 0 rgba(255,255,255,.55), 0 2px 8px rgba(0,0,0,.12)",
    } satisfies CSSProperties,
    ratingPlateColor: (plateId: string): CSSProperties => ({
        background: plateColors[plateId] ?? plateColors["01"],
    }),
    section: {
        marginTop: 16,
    } satisfies CSSProperties,
    sectionTitle: {
        display: "flex",
        alignItems: "baseline",
        gap: 15,
        margin: "30px 0 10px",
        fontSize: 24,
        lineHeight: 1.2,
        fontWeight: "bold",
    } satisfies CSSProperties,
    stats: {
        display: "inline-flex",
        gap: 10,
        flexWrap: "wrap",
        fontSize: 14.4,
        fontWeight: "normal",
        color: "#888",
    } satisfies CSSProperties,
    grid: {
        display: "grid",
        gridTemplateColumns: "repeat(5, 210px)",
        gap: 12,
        marginTop: 20,
        width: "100%",
        justifyContent: "center",
        boxSizing: "border-box",
    } satisfies CSSProperties,
    cardWrapper: {
        width: 210,
        padding: "5px 5px",
        boxSizing: "border-box",
        backgroundColor: "transparent",
    } satisfies CSSProperties,
    card: (showDxScore: boolean): CSSProperties => ({
        width: "100%",
        minHeight: showDxScore ? 90 : 85,
        display: "flex",
        overflow: "hidden",
        borderRadius: 12,
        background: "#f0f0f0",
        boxShadow: "0 1px 3px rgba(0,0,0,.22), 0 2px 8px rgba(0,0,0,.12)",
    }),
    songJacketSection: {
        flex: "0 0 40%",
        position: "relative",
    } satisfies CSSProperties,
    songJacketImage: {
        width: "100%",
        height: "100%",
        objectFit: "cover",
        objectPosition: "center",
    } satisfies CSSProperties,
    details: (_showDxScore: boolean): CSSProperties => ({
        flex: "0 0 60%",
        padding: 6,
        color: "#333",
        display: "flex",
        flexDirection: "column",
        height: "100%",
        width: "60%",
        boxSizing: "border-box",
    }),
    resultHeader: (showDxScore: boolean): CSSProperties => ({
        height: showDxScore ? 12 : 15,
        flexShrink: 0,
    }),
    headerPill: (_showDxScore: boolean): CSSProperties => ({
        display: "flex",
        height: "100%",
        borderRadius: 7.5,
        overflow: "hidden",
        marginLeft: "1.5%",
        width: "97.5%",
    }),
    pillSection: {
        flex: 1,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontWeight: "bold",
        fontSize: 9.5,
        textAlign: "center",
        padding: "0 2.25px",
        lineHeight: 1,
    } satisfies CSSProperties,
    charttype: (chartType: string): CSSProperties => ({
        background: chartType === "DX" ? "#fff" : "#63acf8",
        fontWeight: 1000,
        flexGrow: 0.5,
        color: chartType === "DX" ? "transparent" : "#fff",
    }),
    level: (levelIndex: number): CSSProperties => ({
        color: "#fff",
        flexGrow: 0.75,
        background: difficultyColors[levelIndex] ?? "#96d767",
    }),
    points: {
        background: "linear-gradient(90deg, #ff9933 0%, #ff6600 100%)",
        color: "#fff",
    } satisfies CSSProperties,
    songName: (showDxScore: boolean): CSSProperties => ({
        fontSize: showDxScore ? 9 : 10.5,
        fontWeight: "bold",
        marginTop: showDxScore ? 1.3 : 1.5,
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
        flexShrink: 0,
        width: "100%",
        maxWidth: "100%",
        display: "block",
        boxSizing: "border-box",
    }),
    achievement: (showDxScore: boolean): CSSProperties => ({
        fontSize: showDxScore ? 16.5 : 19.5,
        fontWeight: "bold",
        lineHeight: 1,
        marginBottom: showDxScore ? 1.3 : 1.5,
        flexShrink: 0,
        whiteSpace: "nowrap",
        overflow: "hidden",
        width: "100%",
        maxWidth: "100%",
        display: "block",
        boxSizing: "border-box",
    }),
    percentageMark: (showDxScore: boolean): CSSProperties => ({
        fontSize: showDxScore ? 11.5 : 12,
    }),
    achievementBadges: {
        display: "flex",
        justifyContent: "space-around",
        alignItems: "center",
        flexShrink: 0,
    } satisfies CSSProperties,
    rankAchievement: (showDxScore: boolean): CSSProperties => ({
        width: showDxScore ? 19.5 : 22.5,
        height: showDxScore ? 19.5 : 22.5,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: "transparent",
        border: "none",
        boxShadow: "none",
        flexGrow: 0.4,
        position: "relative",
    }),
    fcAchievement: (showDxScore: boolean): CSSProperties => ({
        width: showDxScore ? 19.5 : 22.5,
        height: showDxScore ? 19.5 : 22.5,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: "#ddd",
        borderRadius: "50%",
        position: "relative",
        overflow: "hidden",
    }),
    syncAchievement: (showDxScore: boolean): CSSProperties => ({
        width: showDxScore ? 19.5 : 22.5,
        height: showDxScore ? 19.5 : 22.5,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: "#ddd",
        borderRadius: "50%",
        position: "relative",
        overflow: "hidden",
    }),
    achievementIcon: {
        width: "100%",
        height: "100%",
        objectFit: "contain",
        position: "absolute",
    } satisfies CSSProperties,
    dxScoreStarsMini: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        lineHeight: 1,
        gap: 0.5,
        position: "absolute",
        bottom: -4,
        left: "50%",
        transform: "translateX(-50%)",
        zIndex: 1,
    } satisfies CSSProperties,
    dxScoreStarMini: {
        height: 7,
        width: "auto",
        margin: "0 0.5px",
    } satisfies CSSProperties,
    dxScore: {
        fontSize: 9,
        display: "flex",
        alignItems: "center",
        marginTop: "0.2em",
        lineHeight: 1,
    } satisfies CSSProperties,
    dxScoreLabel: {
        marginLeft: "auto",
        lineHeight: 1,
    } satisfies CSSProperties,
    dxScoreStar: {
        height: "1em",
        width: "auto",
        marginRight: 1,
    } satisfies CSSProperties,
};
