import type { CSSProperties } from "react";
import type { B50RenderChart, B50RenderPayload } from "./b50-payload";

const WIDTH = 1175;
const HEIGHT = 1365;
const DEFAULT_SITE_ORIGIN = "https://salt.realtvop.top";

export const B50_RENDER_SIZE = {
    width: WIDTH,
    height: HEIGHT,
};

export interface B50RenderImageOptions {
    siteOrigin?: string;
}

interface B50RenderImageProps {
    payload: B50RenderPayload;
    options?: B50RenderImageOptions;
}

export function B50RenderImage({ payload, options = {} }: B50RenderImageProps) {
    const siteOrigin = normalizeOrigin(options.siteOrigin ?? DEFAULT_SITE_ORIGIN);
    const modeLabel = payload.modeLabel && payload.modeLabel !== "B50" ? payload.modeLabel : "";

    return (
        <main style={styles.page(siteOrigin)}>
            <section style={styles.header}>
                <div style={styles.player}>
                    <div style={styles.playerNames}>
                        <div style={styles.name}>{payload.playerName}</div>
                        {payload.playerSecondaryName ? (
                            <div style={styles.secondary}>{payload.playerSecondaryName}</div>
                        ) : null}
                    </div>
                    {typeof payload.playerRating === "number" ? (
                        <RatingPlate rating={payload.playerRating} />
                    ) : null}
                    {modeLabel ? <div style={styles.mode}>{modeLabel}</div> : null}
                </div>
                <div style={styles.brand}>
                    <div>
                        <div style={styles.generated}>Generated by SaltNet</div>
                        <div style={styles.url}>salt.realtvop.top</div>
                    </div>
                    <img style={styles.logo} src={`${siteOrigin}/favicon.png`} />
                </div>
            </section>

            <ScoreSection
                title="旧版本成绩"
                charts={payload.sd}
                showDxScore={payload.showDxScore}
                siteOrigin={siteOrigin}
            />
            <ScoreSection
                title="新版本成绩"
                charts={payload.dx}
                showDxScore={payload.showDxScore}
                siteOrigin={siteOrigin}
            />
        </main>
    );
}

function ScoreSection({
    title,
    charts,
    showDxScore,
    siteOrigin,
}: {
    title: string;
    charts: B50RenderChart[];
    showDxScore: boolean;
    siteOrigin: string;
}) {
    if (!charts.length) return null;
    const stats = getStats(charts);

    return (
        <section style={styles.section}>
            <h2 style={styles.sectionTitle}>
                {title}
                <span style={styles.stats}>
                    <span>{stats.total}</span>
                    <span>{stats.levelRange}</span>
                    <span>平均: {stats.average}</span>
                    <span>中位数: {stats.median}</span>
                    <span>极差: {stats.range}</span>
                </span>
            </h2>
            <div style={styles.grid}>
                {charts.map((chart, index) => (
                    <ScoreCard
                        key={`${chart.songId}-${chart.levelIndex}-${index}`}
                        chart={chart}
                        showDxScore={showDxScore}
                        siteOrigin={siteOrigin}
                    />
                ))}
            </div>
        </section>
    );
}

function ScoreCard({
    chart,
    showDxScore,
    siteOrigin,
}: {
    chart: B50RenderChart;
    showDxScore: boolean;
    siteOrigin: string;
}) {
    const achievement =
        typeof chart.achievements === "number" ? chart.achievements.toFixed(4) : "-";
    const stars = <DxStars chart={chart} showDxScore={showDxScore} siteOrigin={siteOrigin} />;

    return (
        <article style={styles.card(showDxScore)}>
            <img style={styles.cover} src={getCoverUrl(chart.songId)} />
            <div style={styles.details}>
                <div style={styles.pill(showDxScore)}>
                    <span style={{ ...styles.pillPart(showDxScore), ...styles.type(chart.type) }}>
                        {chart.type}
                    </span>
                    <span
                        style={{
                            ...styles.pillPart(showDxScore),
                            ...styles.level(chart.levelIndex),
                        }}
                    >
                        {formatNumber(chart.ds, 1)}
                    </span>
                    <span style={{ ...styles.pillPart(showDxScore), ...styles.rating }}>
                        {Math.round(chart.ra)}
                    </span>
                </div>
                <div style={styles.title(showDxScore)}>{chart.title}</div>
                <div style={styles.achievement(showDxScore)}>
                    {achievement}
                    <span style={styles.percent(showDxScore)}>%</span>
                </div>
                <div style={styles.badges}>
                    <div style={styles.rankBadge(showDxScore)}>
                        {chart.rate ? (
                            <img
                                style={styles.badgeImage}
                                src={`${siteOrigin}/icons/${chart.rate.replace("p", "plus")}.png`}
                            />
                        ) : (
                            stars
                        )}
                    </div>
                    <div style={styles.roundBadge(showDxScore)}>
                        {chart.fc ? (
                            <img
                                style={styles.badgeImage}
                                src={`${siteOrigin}/icons/music_icon_${chart.fc}.png`}
                            />
                        ) : null}
                    </div>
                    <div style={styles.roundBadge(showDxScore)}>
                        {chart.fs ? (
                            <img
                                style={styles.badgeImage}
                                src={`${siteOrigin}/icons/music_icon_${chart.fs.replace("sd", "dx")}.png`}
                            />
                        ) : null}
                    </div>
                </div>
                {showDxScore ? (
                    <div style={styles.dxScore}>
                        {stars}
                        <span style={styles.dxScoreLabel}>
                            {chart.deluxeScore ?? "-"} / {chart.deluxeScoreMax ?? "-"}
                        </span>
                    </div>
                ) : null}
            </div>
        </article>
    );
}

function DxStars({
    chart,
    showDxScore,
    siteOrigin,
}: {
    chart: B50RenderChart;
    showDxScore: boolean;
    siteOrigin: string;
}) {
    if (typeof chart.deluxeScore !== "number" || typeof chart.deluxeScoreMax !== "number") {
        return null;
    }

    const tier = getDeluxeScoreTier(chart.deluxeScore, chart.deluxeScoreMax);
    if (!tier) return null;

    const star = tier < 3 ? "star1" : tier < 5 ? "star2" : "star3";
    const starStyle = showDxScore ? styles.star : styles.miniStar;

    return (
        <>
            {Array.from({ length: tier }, (_, index) => (
                <img key={index} style={starStyle} src={`${siteOrigin}/icons/${star}.png`} />
            ))}
        </>
    );
}

function RatingPlate({ rating }: { rating: number }) {
    return (
        <div style={{ ...styles.ratingPlate, ...styles.ratingPlateColor(getPlateId(rating)) }}>
            {Math.round(rating).toString()}
        </div>
    );
}

function getStats(charts: B50RenderChart[]) {
    const ratings = charts.map(chart => Math.round(chart.ra)).sort((a, b) => a - b);
    const constants = charts.map(chart => chart.ds).sort((a, b) => a - b);
    const total = ratings.reduce((sum, rating) => sum + rating, 0);
    const middle = Math.floor(ratings.length / 2);
    const median =
        ratings.length % 2 === 0 ? (ratings[middle - 1] + ratings[middle]) / 2 : ratings[middle];

    return {
        total,
        average: (total / ratings.length).toFixed(2),
        median,
        range: ratings[ratings.length - 1] - ratings[0],
        levelRange: `${formatNumber(constants[0], 1)}~${formatNumber(constants[constants.length - 1], 1)}`,
    };
}

function getCoverUrl(songId: number): string {
    return `https://meta.salt.realtvop.top/covers/${padId(songId % 10000, 6)}.png`;
}

function padId(id: number, length: number): string {
    return id.toString().padStart(length, "0");
}

function getPlateId(rating: number): string {
    const levels = [1000, 2000, 4000, 7000, 10000, 12000, 13000, 14000, 14500, 15000];
    if (rating < levels[0]) return "01";
    if (rating >= levels[9]) return "11";
    const plateIndex = levels.findIndex(
        (threshold, index) => rating >= threshold && rating < levels[index + 1]
    );
    return plateIndex >= 0 ? (plateIndex + 2).toString().padStart(2, "0") : "00";
}

function getDeluxeScoreTier(deluxeScore: number, deluxeScoreMax: number): number {
    const percent = deluxeScore / deluxeScoreMax;
    if (percent >= 0.97) return 5;
    if (percent >= 0.95) return 4;
    if (percent >= 0.93) return 3;
    if (percent >= 0.9) return 2;
    if (percent >= 0.85) return 1;
    return 0;
}

function formatNumber(value: number, digits: number): string {
    return value.toFixed(digits);
}

function normalizeOrigin(origin: string): string {
    return origin.replace(/\/+$/, "");
}

const difficultyColors: Record<number, string> = {
    0: "#96d767",
    1: "#eeba41",
    2: "#ef888f",
    3: "#b54fdf",
    4: "#d3acf9",
    5: "#ee78f6",
    10: "#ff6b9b",
};

const plateColors: Record<string, string> = {
    "01": "linear-gradient(90deg, #6f7880, #a7b0b8)",
    "02": "linear-gradient(90deg, #415d7d, #79a7d8)",
    "03": "linear-gradient(90deg, #3b8752, #91d977)",
    "04": "linear-gradient(90deg, #9a6a24, #eac267)",
    "05": "linear-gradient(90deg, #a85c67, #f39aa4)",
    "06": "linear-gradient(90deg, #8253a3, #d29af4)",
    "07": "linear-gradient(90deg, #b45d22, #ffb15e)",
    "08": "linear-gradient(90deg, #2f7e8f, #60d6e8)",
    "09": "linear-gradient(90deg, #bc8d17, #ffe066)",
    "10": "linear-gradient(90deg, #d24f7f, #ff9bbd)",
    "11": "linear-gradient(90deg, #1e1e2c, #8e92e1)",
};

const styles = {
    page: (siteOrigin: string): CSSProperties => ({
        width: WIDTH,
        height: HEIGHT,
        overflow: "hidden",
        padding: "20px 30px 40px",
        color: "#222",
        backgroundColor: "#eef6fb",
        backgroundImage: `linear-gradient(rgba(255,255,255,.72), rgba(255,255,255,.78)), url("${siteOrigin}/b50_background.png")`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        fontFamily: '"Noto Sans SC", "Noto Sans JP", "Noto Sans TC", sans-serif',
        boxSizing: "border-box",
    }),
    header: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 24,
        marginBottom: 24,
    } satisfies CSSProperties,
    player: {
        display: "flex",
        alignItems: "center",
        gap: 22,
        minWidth: 0,
    } satisfies CSSProperties,
    playerNames: {
        display: "flex",
        flexDirection: "column",
        minWidth: 0,
    } satisfies CSSProperties,
    name: {
        fontSize: 32,
        lineHeight: 1.1,
        fontWeight: 800,
        maxWidth: 520,
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
    } satisfies CSSProperties,
    secondary: {
        marginTop: 4,
        fontSize: 15,
        color: "#58616b",
        maxWidth: 520,
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
    } satisfies CSSProperties,
    mode: {
        border: "1px solid rgba(35, 47, 62, .16)",
        background: "rgba(255,255,255,.76)",
        borderRadius: 999,
        padding: "6px 12px",
        fontSize: 16,
        fontWeight: 700,
    } satisfies CSSProperties,
    brand: {
        display: "flex",
        alignItems: "center",
        gap: 9,
        textAlign: "right",
        flexShrink: 0,
    } satisfies CSSProperties,
    generated: {
        fontSize: 16,
        fontWeight: 800,
        marginBottom: -2,
    } satisfies CSSProperties,
    url: {
        fontSize: 13,
        color: "#5d6670",
    } satisfies CSSProperties,
    logo: {
        width: 48,
        height: 48,
    } satisfies CSSProperties,
    ratingPlate: {
        minWidth: 125,
        height: 25,
        borderRadius: 7,
        padding: "2px 8px 0 48px",
        color: "#fcd41b",
        fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
        fontSize: 16,
        fontWeight: 900,
        letterSpacing: 2,
        lineHeight: "23px",
        textAlign: "center",
        boxShadow: "inset 0 1px 0 rgba(255,255,255,.55), 0 2px 8px rgba(0,0,0,.12)",
    } satisfies CSSProperties,
    ratingPlateColor: (plateId: string): CSSProperties => ({
        background: plateColors[plateId] ?? plateColors["01"],
    }),
    section: {
        marginTop: 16,
    } satisfies CSSProperties,
    sectionTitle: {
        display: "flex",
        alignItems: "baseline",
        gap: 15,
        margin: "0 0 12px",
        fontSize: 24,
        lineHeight: 1.2,
        fontWeight: 800,
    } satisfies CSSProperties,
    stats: {
        display: "flex",
        gap: 10,
        flexWrap: "wrap",
        fontSize: 14,
        fontWeight: 400,
        color: "#47515c",
    } satisfies CSSProperties,
    grid: {
        display: "grid",
        gridTemplateColumns: "repeat(5, 210px)",
        gap: 12,
        justifyContent: "center",
    } satisfies CSSProperties,
    card: (showDxScore: boolean): CSSProperties => ({
        width: 210,
        minHeight: showDxScore ? 90 : 85,
        display: "flex",
        overflow: "hidden",
        borderRadius: 4,
        background: "#f0f0f0",
        boxShadow: "0 1px 3px rgba(0,0,0,.22), 0 2px 8px rgba(0,0,0,.12)",
    }),
    cover: {
        width: "40%",
        objectFit: "cover",
        objectPosition: "center",
        flex: "0 0 40%",
    } satisfies CSSProperties,
    details: {
        width: "60%",
        display: "flex",
        flexDirection: "column",
        padding: 6,
        minWidth: 0,
    } satisfies CSSProperties,
    pill: (showDxScore: boolean): CSSProperties => ({
        display: "flex",
        height: showDxScore ? 12 : 15,
        borderRadius: 8,
        overflow: "hidden",
        marginLeft: 2,
        width: "calc(100% - 2px)",
        flexShrink: 0,
    }),
    pillPart: (showDxScore: boolean): CSSProperties => ({
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontWeight: 900,
        fontSize: showDxScore ? 9.5 : 9,
        lineHeight: 1,
        padding: "0 3px",
        color: "#fff",
    }),
    type: (chartType: string): CSSProperties => ({
        flex: 0.5,
        background: chartType === "DX" ? "#fff" : "#63acf8",
        color: chartType === "DX" ? "#eb5639" : "#fff",
    }),
    level: (levelIndex: number): CSSProperties => ({
        flex: 0.75,
        background: difficultyColors[levelIndex] ?? "#96d767",
    }),
    rating: {
        flex: 1,
        background: "linear-gradient(90deg, #ff9933 0%, #ff6600 100%)",
    } satisfies CSSProperties,
    title: (showDxScore: boolean): CSSProperties => ({
        marginTop: showDxScore ? 2 : 3,
        fontSize: showDxScore ? 9 : 10.5,
        fontWeight: 800,
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
    }),
    achievement: (showDxScore: boolean): CSSProperties => ({
        margin: "1px 0 2px",
        fontSize: showDxScore ? 16.5 : 19.5,
        lineHeight: 1,
        fontWeight: 900,
        whiteSpace: "nowrap",
        overflow: "hidden",
    }),
    percent: (showDxScore: boolean): CSSProperties => ({
        fontSize: showDxScore ? 11.5 : 12,
    }),
    badges: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-around",
    } satisfies CSSProperties,
    rankBadge: (showDxScore: boolean): CSSProperties => ({
        width: showDxScore ? 19.5 : 22.5,
        height: showDxScore ? 19.5 : 22.5,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
    }),
    roundBadge: (showDxScore: boolean): CSSProperties => ({
        width: showDxScore ? 19.5 : 22.5,
        height: showDxScore ? 19.5 : 22.5,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
        borderRadius: "50%",
        background: "#ddd",
        overflow: "hidden",
    }),
    badgeImage: {
        width: "100%",
        height: "100%",
        objectFit: "contain",
    } satisfies CSSProperties,
    miniStar: {
        width: "auto",
        height: 7,
        margin: "0 .5px",
    } satisfies CSSProperties,
    dxScore: {
        display: "flex",
        alignItems: "center",
        marginTop: 2,
        fontSize: 9,
        lineHeight: 1,
        minHeight: 10,
    } satisfies CSSProperties,
    dxScoreLabel: {
        marginLeft: "auto",
    } satisfies CSSProperties,
    star: {
        width: "auto",
        height: 9,
        marginRight: 1,
    } satisfies CSSProperties,
};
